GLMV.AppWeb/Controllers/CategoryController.cs
using GLMV.Application.Services;
using GLMV.Domain.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GLMV.AppWeb.Controllers
{
    //   [Authorize(Roles = "SALESPERSON")]  - bão consegui colocar o authorize para funcionar
    [Authorize]
    public class CategoryController : Controller
    {
        private readonly CategoryService _categoriaService;

        public CategoryController(CategoryService categoriaService)
        {
            _categoriaService = categoriaService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _categoriaService.GetAllAsync());
        }


        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = _categoriaService.GetById(id);

            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Description,Id")] Category category)
        {
            if (ModelState.IsValid)
            {
                category.DataCadastro = DateOnly.FromDateTime(DateTime.Now);
                category.DataAtualizacao = DateOnly.FromDateTime(DateTime.Now);

                _categoriaService.AddAsync(category);
                await _categoriaService.SaveASync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }


        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = _categoriaService.GetById(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Description,Id,DataCadastro,DataAtualizacao")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    category.DataAtualizacao = DateOnly.FromDateTime(DateTime.Now);
                    _categoriaService.Update(category);
                    await _categoriaService.SaveASync();
                }
                catch
                {
                    throw;
                }

                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = _categoriaService.GetById(id);

            if (_categoriaService.isCategoryContainProducts(id))
            {
                TempData["StatusCategoriaErro"] = "Categoria Contem Produtos! Exclusão não é possível";

                return RedirectToAction(nameof(Index));
            }

            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = _categoriaService.GetById(id);
            if (category != null)
            {
                _categoriaService.DeleteAsync(category);
            }

            await _categoriaService.SaveASync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists()
        {
            return _categoriaService.isCategoryExists();
        }
    }
}

GLMV.AppWeb/Controllers/GestaoLojaController.cs
using GLMV.Application.Services;
using GLMV.Domain.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GLMV.AppWeb.Controllers
{

    [Authorize]
    public class GestaoLojaController : Controller
    {
        private readonly ProductService _productService;
        private readonly SalesPersonService _salesPersonService;
        private readonly CategoryService _categoriaService;

        public GestaoLojaController(SalesPersonService salesPersonService, ProductService productService, CategoryService categoryService)
        {
            _productService = productService;
            _salesPersonService = salesPersonService;
            _categoriaService = categoryService;
        }

        [HttpGet]
        public IActionResult Index(string id)
        {
            var listCategories = _categoriaService.GetAllAsync();

            var model = _salesPersonService.GetSalesPersonProduct(id);

            if (model == null)
                return NotFound();


            return View(model);
        }

        [HttpGet]
        public async Task<PartialViewResult> GetProductsBySalesPerson(string id)
        {
            var salesPerson = _salesPersonService.GetSalesPersonProduct(id);

            if (salesPerson == null)
                return PartialView("list-products", new List<Product>());


            return PartialView("list-products", salesPerson.Products);
        }

    }
}

GLMV.AppWeb/Controllers/SalesPersonsController.cs
using GLMV.Application.Services;
using GLMV.Domain.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GLMV.AppWeb.Controllers
{

    //   [Authorize(Roles = "SALESPERSON")]  - bão consegui colocar o authorize para funcionar
    [Authorize]
    public class SalesPersonsController : Controller
    {
        private readonly SalesPersonService _service;

        public SalesPersonsController(SalesPersonService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var salesPerson = _service.GetByIdString(id);
            if (salesPerson == null)
            {
                return NotFound();
            }
            return View(salesPerson);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,FirstName,LastName,Email")] SalesPerson salesPerson)
        {
            if (id != salesPerson.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _service.Update(salesPerson);
                    await _service.SaveASync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SalesPersonExists(salesPerson.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "GestaoLoja", new { Id = salesPerson.Id });
            }
            return RedirectToAction("Index", "GestaoLoja", new { Id = salesPerson.Id });

        }

        private bool SalesPersonExists(string id)
        {
            return _service.isSalesPersonExists(id);
        }
    }
}

GLMV.AppWeb/Views/GestaoLoja/Index.cshtml
@model GLMV.Domain.Models.SalesPerson;

@{
    ViewData["Title"] = "Market Place - Area do Vendedor ";
}

<h5 class="text-center">@ViewData["Title"]</h5>
<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <div class="card">
                <div class="card-body text-center">
                    <h5 class="card-title text-center">Vendedor</h5>
                    <p class="card-text text-center">Gerencie os seus dados</p>
                    <a class="btn btn-primary" asp-controller="SalesPersons" asp-route-id="@Model.Id" asp-action="Edit">Dados Vendedor</a>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="card">
                <div class="card-body text-center">
                    <h5 class="card-title text-center">Categorias</h5>
                    <p class="card-text text-center">Gerencie a lista de categorias do sistema.</p>
                    <a class="btn btn-primary" asp-controller="Category" asp-action="Index">Categorias</a>
                </div>
            </div>
        </div>
    </div>
    <hr />
    <center>Lista de Produtos - Vendedor @Model.FirstName</center>
    <hr />
    <p>
        <a asp-controller="products" asp-action="create-product" asp-route-id="@Model.Id" class="btn btn-info">Adicionar</a>
    </p>
    <hr />

    @if (TempData["StatusCategoriaSucesso"] != null)
    {
        var mensagem = TempData["StatusCategoriaSucesso"];

        <div class="alert-info">@Html.Raw(mensagem)</div>
    }

    @if (TempData["StatusCategoriaErro"] != null)
    {
        var mensagem = TempData["StatusCategoriaErro"];

        <div id="msg_box" class="alert alert-danger">
            @Html.Raw(mensagem)
        </div>
    }
    
    @await Html.PartialAsync("salesperson-products", Model.Products)
</div>

GLMV.AppWeb/Views/GestaoLoja/salesperson-products.cshtml
@model IList<GLMV.Domain.Models.Product>;


<table class="table table-striped">
    <thead>
        <tr>
            <th class="text-center">Descrição</th>
            <th class="text-center">Categoria</th>
            <th class="text-center">Valor R$</th>
            <th class="text-center">Quantidade</th>
            <th class="text-center">Valor Estoque Total R$</th>
            <th class="text-center">Imagem</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var product in Model)
        {
            
            <tr>
                <td>@product.Title</td>
                <td class="text-center">@product.Category.Description</td>
                <td class="text-center">R$ @product.Price.ToString("N2")</td>
                <td class="text-center">@product.Quantity</td>
                <td class="text-center">R$ @((product.Quantity * product.Price).ToString("N2", new System.Globalization.CultureInfo("pt-BR"))) </td>
                <td class="text-center"><img src="../../@product.ImageUrl" width="70px"></td>
                <td>
                    <a asp-controller="products" asp-action="edit-product" asp-route-id="@product.Id"   class="btn btn-primary">Alterar</a> |
                    <a asp-controller="products" asp-action="detail-product" asp-route-id="@product.Id" class="btn btn-info">Detalhes</a> |
                    <a asp-controller="products" asp-action="delete-product" asp-route-id="@product.Id" class="btn btn-danger"> Excluir</a>
                </td>
            </tr>
        }
    </tbody>
</table>