GLMV.AppWeb/Controllers/CategoryController.cs
using GLMV.Application.Services;
using GLMV.Domain.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GLMV.AppWeb.Controllers
{
    //   [Authorize(Roles = "SALESPERSON")]  - bão consegui colocar o authorize para funcionar
    [Authorize]
    public class CategoryController : Controller
    {
        private readonly CategoryService _categoriaService;

        public CategoryController(CategoryService categoriaService)
        {
            _categoriaService = categoriaService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _categoriaService.GetAllAsync());
        }


        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = _categoriaService.GetById(id);

            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Description,Id")] Category category)
        {
            if (ModelState.IsValid)
            {
                category.DataCadastro = DateOnly.FromDateTime(DateTime.Now);
                category.DataAtualizacao = DateOnly.FromDateTime(DateTime.Now);

                _categoriaService.AddAsync(category);
                await _categoriaService.SaveASync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }


        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = _categoriaService.GetById(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Description,Id,DataCadastro,DataAtualizacao")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    category.DataAtualizacao = DateOnly.FromDateTime(DateTime.Now);
                    _categoriaService.Update(category);
                    await _categoriaService.SaveASync();
                }
                catch
                {
                    throw;
                }

                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = _categoriaService.GetById(id);

            if (_categoriaService.isCategoryContainProducts(id))
            {
                TempData["StatusCategoriaErro"] = "Categoria Contem Produtos! Exclusão não é possível";

                return RedirectToAction(nameof(Index));
            }

            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = _categoriaService.GetById(id);
            if (category != null)
            {
                _categoriaService.DeleteAsync(category);
            }

            await _categoriaService.SaveASync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists()
        {
            return _categoriaService.isCategoryExists();
        }
    }
}

GLMV.AppWeb/Controllers/GestaoLojaController.cs
using GLMV.Application.Services;
using GLMV.Domain.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GLMV.AppWeb.Controllers
{

    [Authorize]
    public class GestaoLojaController : Controller
    {
        private readonly ProductService _productService;
        private readonly SalesPersonService _salesPersonService;
        private readonly CategoryService _categoriaService;

        public GestaoLojaController(SalesPersonService salesPersonService, ProductService productService, CategoryService categoryService)
        {
            _productService = productService;
            _salesPersonService = salesPersonService;
            _categoriaService = categoryService;
        }

        [HttpGet]
        public IActionResult Index(string id)
        {
            var listCategories = _categoriaService.GetAllAsync();

            var model = _salesPersonService.GetSalesPersonProduct(id);

            if (model == null)
                return NotFound();


            return View(model);
        }

        [HttpGet]
        public async Task<PartialViewResult> GetProductsBySalesPerson(string id)
        {
            var salesPerson = _salesPersonService.GetSalesPersonProduct(id);

            if (salesPerson == null)
                return PartialView("list-products", new List<Product>());


            return PartialView("list-products", salesPerson.Products);
        }

    }
}

GLMV.AppWeb/Views/Category/Create.cshtml
@model GLMV.Domain.Models.Category


@{
    ViewData["Title"] = "Inclusão";
}

<h4>@ViewData["Title"]</h4>
<hr />
<h4>Categoria</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
           <hr/>
            <div class="text-center">
                <input type="submit" value="Confirmar" class="btn btn-primary" /> |  <a asp-action="Index" class="btn btn-warning">Retornar</a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GLMV.AppWeb/Views/Category/Delete.cshtml
@model GLMV.Domain.Models.Category

@{
    ViewData["Title"] = "Exclusão";
}

<h4>@ViewData["Title"]</h4>
<hr />
<h4>Categoria</h4>
<hr />
<h3>Você realmente deseja realizar a exclusão?</h3>
<div>
    <h4>Categoria</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataCadastro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataCadastro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataAtualizacao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataAtualizacao)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Excluir" class="btn btn-danger" /> |  <a asp-action="Index" class="btn btn-warning">Retornar</a>
       
    </form>
</div>

GLMV.AppWeb/Views/Category/Details.cshtml
@model GLMV.Domain.Models.Category

@{
    ViewData["Title"] = "Detalhes";
}

<h4>@ViewData["Title"]</h4>
<hr />
<h4>Categoria</h4>
<hr />
<div>
    <h4>Categoria</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataCadastro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataCadastro)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DataAtualizacao)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataAtualizacao)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-primary">Alterar</a> | <a asp-action="Index" class="btn btn-warning">Retornar</a>
</div>

GLMV.AppWeb/Views/Category/Edit.cshtml
@model GLMV.Domain.Models.Category

@{
    ViewData["Title"] = "Alteração";
}

<h4>@ViewData["Title"]</h4>
<hr />
<h4>Categoria</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <hr/>
            <div class="text-center">
                <input type="submit" value="Confirmar" class="btn btn-primary" />  |  <a asp-action="Index" class="btn btn-warning">Retornar</a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GLMV.AppWeb/Views/Category/Index.cshtml
@using GLMV.Domain.Models
@model IEnumerable<Category>

@{
    ViewData["Title"] = "Categorias";

    var UserId = Context.Session.GetString("UserId");

    var Name = Context.Session.GetString("Name");

}

<hr />
<h4>Categorias</h4>
<hr />

<p>


@if (@TempData["StatusCategoriaErro"] != null){
         
        var mensagem = TempData["StatusCategoriaErro"];

    <div id="msg_box" class="alert alert-danger">
        @Html.Raw(mensagem)
    </div>
    
}

<a  asp-action="Create" class="btn btn-info">Adicionar</a> |  <a asp-controller="GestaoLoja" asp-action="Index" asp-route-id="@UserId" class="btn btn-warning">Retornar</a>

</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataCadastro)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataAtualizacao)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataCadastro)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataAtualizacao)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary">Alterar</a> |
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info">Detalhes</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Excluir</a>
                </td>
            </tr>
        }

    </tbody>
</table>